window.swapImages = swapImages;
window.footerBarLogo = footerBarLogo;
window.heroWithSlider = heroWithSlider;
window.lenisScroll = lenisScroll;
window.heroWithVideo = heroWithVideo;
window.playVideo = playVideo;
window.sliderGallery = sliderGallery;
window.galleryLightbox = galleryLightbox;
window.elementAppears = elementAppears;
window.services = services;
window.itemSiblings = itemSiblings;
window.playVideoOnHover = playVideoOnHover;
window.mediaFadein = mediaFadein;

preloader();
lenisScroll();
barbaPageTransition();
swapImages();
toggleMenu();
footerBarLogo();
heroWithSlider();
heroWithVideo();
playVideo();
sliderGallery();
galleryLightbox();
elementAppears();
services();
itemSiblings();
highlights();
playVideoOnHover();
mediaFadein();
